In [1]:
import numpy as np

In [2]:
a = [10,20,30,40]

In [3]:
type(a)

list

In [5]:
x = np.array(a)


In [6]:
print(x)

[10 20 30 40]


In [7]:
type(x)

numpy.ndarray

In [8]:
a = [1,2,3,4]
b = [10,20,30,40]
x = np.array([a,b])

In [9]:
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [11]:
a = [1,2,3]
b = [10,20,30]
x = np.array([a,b])

In [12]:
print(x)

[[ 1  2  3]
 [10 20 30]]


In [13]:
x = np.array([1,2,3,4], dtype = np.float32)
print(x)

[1. 2. 3. 4.]


In [14]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [18]:
x = np.random.rand(2,5)

In [19]:
print(x)

[[0.92696705 0.8161861  0.04065699 0.02845677 0.11315021]
 [0.02840484 0.28403759 0.92644758 0.61778593 0.24825092]]


In [20]:
np.random.rand??

In [21]:
np.random.randint(1,20, size = (3,3))

array([[17, 19,  6],
       [ 2, 12, 19],
       [ 9, 15, 14]])

In [22]:
np.random.randint??

In [23]:
np.random.randn(2,5)

array([[ 1.73285466,  0.38980763,  0.19495121, -1.77756132, -0.51492753],
       [-0.36003461,  0.23669955, -1.35399258, -0.26380889, -0.88952823]])

In [24]:
np.random.randn??



In [25]:
np.random.choice([2,3,4,7,8,10])

np.int64(2)

In [26]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [27]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [28]:
x = np.eye(4, k = -1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
np.eye??

In [29]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [30]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [31]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
a = [10,20,30,40,50]
x = np.array(a)
print(x)

[10 20 30 40 50]


In [33]:
x.ndim

1

In [34]:
b = [1,2,3,4,5]
y = np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [35]:
y.ndim

2

In [36]:
y.shape

(2, 5)

In [37]:
y.size


10

In [38]:
a = np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [39]:
np.reshape(a, (2,2))

array([[ 3,  6],
       [ 9, 12]])

In [40]:
a.reshape(2,2)

array([[ 3,  6],
       [ 9, 12]])

In [41]:
x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
x.size

15

In [43]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [44]:
x = np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [45]:
y = x.reshape(3,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [46]:
z = np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [47]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [48]:
a = np.arange(1,10)

In [49]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [50]:
a[2:6]

array([3, 4, 5, 6])

In [51]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
x[1,2]

np.int64(6)

In [54]:
x[1][2]

np.int64(6)

In [52]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [56]:
a = np.arange(1,6)
b = np.arange(6,11)

In [57]:
print(a)

[1 2 3 4 5]


In [58]:
print(b)

[ 6  7  8  9 10]


In [59]:
x = np.vstack((a,b))

In [61]:
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [62]:
x = np.hstack((a,b))

In [63]:
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [64]:
a = np.arange(1,10).reshape(3,3)

In [65]:
b = np.arange(10,19).reshape(3,3)

In [66]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [68]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [69]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])